//
//  File 2.swift
//
//
//  Created by Coen ten Thije Boonkkamp on 19/07/2024.
//

import Foundation
import Language

extension Translated {
    public init(
        _ default: A
    ) {
        self = .init(default: `default`, dictionary: [:])
    }
}

extension Translated {
    public init(
        _ all: (Language) -> A
    ) {
        
        self.default = all(.english)
        self.dictionary = [:]
        for language in Language.allCases {
            self.dictionary = [language:all(language)]
        }
    }
}

extension Translated {
    public init(
        _ `default`: A,
        abkhazian: A? = nil,
        afar: A? = nil,
        afrikaans: A? = nil,
        akan: A? = nil,
        albanian: A? = nil,
        amharic: A? = nil,
        arabic: A? = nil,
        aragonese: A? = nil,
        armenian: A? = nil,
        assamese: A? = nil,
        auEnglish: A? = nil,
        avaric: A? = nil,
        avestan: A? = nil,
        aymara: A? = nil,
        azerbaijani: A? = nil,
        bambara: A? = nil,
        bashkir: A? = nil,
        basque: A? = nil,
        belarusian: A? = nil,
        bengali: A? = nil,
        bihari: A? = nil,
        bislama: A? = nil,
        bosnian: A? = nil,
        breton: A? = nil,
        bulgarian: A? = nil,
        burmese: A? = nil,
        catalan: A? = nil,
        caEnglish: A? = nil,
        chamorro: A? = nil,
        chechen: A? = nil,
        chinese: A? = nil,
        chuvash: A? = nil,
        cornish: A? = nil,
        corsican: A? = nil,
        cree: A? = nil,
        croatian: A? = nil,
        czech: A? = nil,
        danish: A? = nil,
        dutch: A? = nil,
        dzongkha: A? = nil,
        english: A? = nil,
        esperanto: A? = nil,
        estonian: A? = nil,
        ewe: A? = nil,
        faroese: A? = nil,
        fijian: A? = nil,
        finnish: A? = nil,
        french: A? = nil,
        galician: A? = nil,
        gaelicScottish: A? = nil,
        georgian: A? = nil,
        german: A? = nil,
        greek: A? = nil,
        guarani: A? = nil,
        gujarati: A? = nil,
        haitianCreole: A? = nil,
        hausa: A? = nil,
        hebrew: A? = nil,
        herero: A? = nil,
        hindi: A? = nil,
        hiriMotu: A? = nil,
        hungarian: A? = nil,
        icelandic: A? = nil,
        ido: A? = nil,
        igbo: A? = nil,
        indonesian: A? = nil,
        interlingua: A? = nil,
        interlingue: A? = nil,
        inuktitut: A? = nil,
        inupiak: A? = nil,
        irish: A? = nil,
        italian: A? = nil,
        japanese: A? = nil,
        javanese: A? = nil,
        kannada: A? = nil,
        kanuri: A? = nil,
        kashmiri: A? = nil,
        kazakh: A? = nil,
        khmer: A? = nil,
        kikuyu: A? = nil,
        kinyarwanda: A? = nil,
        kirundi: A? = nil,
        korean: A? = nil,
        komi: A? = nil,
        kongo: A? = nil,
        kurdish: A? = nil,
        kwanyama: A? = nil,
        kyrgyz: A? = nil,
        lao: A? = nil,
        latin: A? = nil,
        latvian: A? = nil,
        limburgish: A? = nil,
        lingala: A? = nil,
        lithuanian: A? = nil,
        lugaKatanga: A? = nil,
        luxembourgish: A? = nil,
        macedonian: A? = nil,
        malagasy: A? = nil,
        malay: A? = nil,
        malayalam: A? = nil,
        maltese: A? = nil,
        manx: A? = nil,
        maori: A? = nil,
        marathi: A? = nil,
        marshallese: A? = nil,
        moldavian: A? = nil,
        mongolian: A? = nil,
        nauru: A? = nil,
        navajo: A? = nil,
        ndonga: A? = nil,
        nepali: A? = nil,
        northernNdebele: A? = nil,
        norwegian: A? = nil,
        norwegianBokmål: A? = nil,
        norwegianNynorsk: A? = nil,
        occitan: A? = nil,
        ojibwe: A? = nil,
        oriya: A? = nil,
        oromo: A? = nil,
        ossetian: A? = nil,
        pāli: A? = nil,
        persian: A? = nil,
        polish: A? = nil,
        portuguese: A? = nil,
        punjabi: A? = nil,
        quechua: A? = nil,
        romanian: A? = nil,
        romansh: A? = nil,
        russian: A? = nil,
        sami: A? = nil,
        samoan: A? = nil,
        sango: A? = nil,
        sanskrit: A? = nil,
        serbian: A? = nil,
        serboCroatian: A? = nil,
        sesotho: A? = nil,
        setswana: A? = nil,
        shona: A? = nil,
        sindhi: A? = nil,
        sinhalese: A? = nil,
        slovak: A? = nil,
        slovenian: A? = nil,
        somali: A? = nil,
        southernNdebele: A? = nil,
        spanish: A? = nil,
        sundanese: A? = nil,
        swahili: A? = nil,
        swati: A? = nil,
        swedish: A? = nil,
        tagalog: A? = nil,
        tahitian: A? = nil,
        tajik: A? = nil,
        tamil: A? = nil,
        tatar: A? = nil,
        telugu: A? = nil,
        thai: A? = nil,
        tibetan: A? = nil,
        tigrinya: A? = nil,
        tonga: A? = nil,
        tsonga: A? = nil,
        turkish: A? = nil,
        turkmen: A? = nil,
        twi: A? = nil,
        ukEnglish: A? = nil,
        ukrainian: A? = nil,
        urdu: A? = nil,
        usEnglish: A? = nil,
        uyghur: A? = nil,
        uzbek: A? = nil,
        venda: A? = nil,
        vietnamese: A? = nil,
        volapük: A? = nil,
        wallon: A? = nil,
        welsh: A? = nil,
        westernFrisian: A? = nil,
        wolof: A? = nil,
        xhosa: A? = nil,
        yoruba: A? = nil,
        zulu: A? = nil
    ) {
        self.dictionary = [:]
        self.default = `default`
        self.dictionary[.abkhazian] = abkhazian
        self.dictionary[.afar] = afar
        self.dictionary[.afrikaans] = afrikaans
        self.dictionary[.akan] = akan
        self.dictionary[.albanian] = albanian
        self.dictionary[.amharic] = amharic
        self.dictionary[.arabic] = arabic
        self.dictionary[.aragonese] = aragonese
        self.dictionary[.armenian] = armenian
        self.dictionary[.assamese] = assamese
        self.dictionary[.auEnglish] = auEnglish
        self.dictionary[.avaric] = avaric
        self.dictionary[.avestan] = avestan
        self.dictionary[.aymara] = aymara
        self.dictionary[.azerbaijani] = azerbaijani
        self.dictionary[.bambara] = bambara
        self.dictionary[.bashkir] = bashkir
        self.dictionary[.basque] = basque
        self.dictionary[.belarusian] = belarusian
        self.dictionary[.bengali] = bengali
        self.dictionary[.bihari] = bihari
        self.dictionary[.bislama] = bislama
        self.dictionary[.bosnian] = bosnian
        self.dictionary[.breton] = breton
        self.dictionary[.bulgarian] = bulgarian
        self.dictionary[.burmese] = burmese
        self.dictionary[.catalan] = catalan
        self.dictionary[.caEnglish] = caEnglish
        self.dictionary[.chamorro] = chamorro
        self.dictionary[.chechen] = chechen
        self.dictionary[.chinese] = chinese
        self.dictionary[.chuvash] = chuvash
        self.dictionary[.cornish] = cornish
        self.dictionary[.corsican] = corsican
        self.dictionary[.cree] = cree
        self.dictionary[.croatian] = croatian
        self.dictionary[.czech] = czech
        self.dictionary[.danish] = danish
        self.dictionary[.dutch] = dutch
        self.dictionary[.dzongkha] = dzongkha
        self.dictionary[.english] = english
        self.dictionary[.esperanto] = esperanto
        self.dictionary[.estonian] = estonian
        self.dictionary[.ewe] = ewe
        self.dictionary[.faroese] = faroese
        self.dictionary[.fijian] = fijian
        self.dictionary[.finnish] = finnish
        self.dictionary[.french] = french
        self.dictionary[.galician] = galician
        self.dictionary[.gaelicScottish] = gaelicScottish
        self.dictionary[.georgian] = georgian
        self.dictionary[.german] = german
        self.dictionary[.greek] = greek
        self.dictionary[.guarani] = guarani
        self.dictionary[.gujarati] = gujarati
        self.dictionary[.haitianCreole] = haitianCreole
        self.dictionary[.hausa] = hausa
        self.dictionary[.hebrew] = hebrew
        self.dictionary[.herero] = herero
        self.dictionary[.hindi] = hindi
        self.dictionary[.hiriMotu] = hiriMotu
        self.dictionary[.hungarian] = hungarian
        self.dictionary[.icelandic] = icelandic
        self.dictionary[.ido] = ido
        self.dictionary[.igbo] = igbo
        self.dictionary[.indonesian] = indonesian
        self.dictionary[.interlingua] = interlingua
        self.dictionary[.interlingue] = interlingue
        self.dictionary[.inuktitut] = inuktitut
        self.dictionary[.inupiak] = inupiak
        self.dictionary[.irish] = irish
        self.dictionary[.italian] = italian
        self.dictionary[.japanese] = japanese
        self.dictionary[.javanese] = javanese
        self.dictionary[.kannada] = kannada
        self.dictionary[.kanuri] = kanuri
        self.dictionary[.kashmiri] = kashmiri
        self.dictionary[.kazakh] = kazakh
        self.dictionary[.khmer] = khmer
        self.dictionary[.kikuyu] = kikuyu
        self.dictionary[.kinyarwanda] = kinyarwanda
        self.dictionary[.kirundi] = kirundi
        self.dictionary[.korean] = korean
        self.dictionary[.komi] = komi
        self.dictionary[.kongo] = kongo
        self.dictionary[.kurdish] = kurdish
        self.dictionary[.kwanyama] = kwanyama
        self.dictionary[.kyrgyz] = kyrgyz
        self.dictionary[.lao] = lao
        self.dictionary[.latin] = latin
        self.dictionary[.latvian] = latvian
        self.dictionary[.limburgish] = limburgish
        self.dictionary[.lingala] = lingala
        self.dictionary[.lithuanian] = lithuanian
        self.dictionary[.lugaKatanga] = lugaKatanga
        self.dictionary[.luxembourgish] = luxembourgish
        self.dictionary[.macedonian] = macedonian
        self.dictionary[.malagasy] = malagasy
        self.dictionary[.malay] = malay
        self.dictionary[.malayalam] = malayalam
        self.dictionary[.maltese] = maltese
        self.dictionary[.manx] = manx
        self.dictionary[.maori] = maori
        self.dictionary[.marathi] = marathi
        self.dictionary[.marshallese] = marshallese
        self.dictionary[.moldavian] = moldavian
        self.dictionary[.mongolian] = mongolian
        self.dictionary[.nauru] = nauru
        self.dictionary[.navajo] = navajo
        self.dictionary[.ndonga] = ndonga
        self.dictionary[.nepali] = nepali
        self.dictionary[.northernNdebele] = northernNdebele
        self.dictionary[.norwegian] = norwegian
        self.dictionary[.norwegianBokmål] = norwegianBokmål
        self.dictionary[.norwegianNynorsk] = norwegianNynorsk
        self.dictionary[.occitan] = occitan
        self.dictionary[.ojibwe] = ojibwe
        self.dictionary[.oriya] = oriya
        self.dictionary[.oromo] = oromo
        self.dictionary[.ossetian] = ossetian
        self.dictionary[.pāli] = pāli
        self.dictionary[.persian] = persian
        self.dictionary[.polish] = polish
        self.dictionary[.portuguese] = portuguese
        self.dictionary[.punjabi] = punjabi
        self.dictionary[.quechua] = quechua
        self.dictionary[.romanian] = romanian
        self.dictionary[.romansh] = romansh
        self.dictionary[.russian] = russian
        self.dictionary[.sami] = sami
        self.dictionary[.samoan] = samoan
        self.dictionary[.sango] = sango
        self.dictionary[.sanskrit] = sanskrit
        self.dictionary[.serbian] = serbian
        self.dictionary[.serboCroatian] = serboCroatian
        self.dictionary[.sesotho] = sesotho
        self.dictionary[.setswana] = setswana
        self.dictionary[.shona] = shona
        self.dictionary[.sindhi] = sindhi
        self.dictionary[.sinhalese] = sinhalese
        self.dictionary[.slovak] = slovak
        self.dictionary[.slovenian] = slovenian
        self.dictionary[.somali] = somali
        self.dictionary[.southernNdebele] = southernNdebele
        self.dictionary[.spanish] = spanish
        self.dictionary[.sundanese] = sundanese
        self.dictionary[.swahili] = swahili
        self.dictionary[.swati] = swati
        self.dictionary[.swedish] = swedish
        self.dictionary[.tagalog] = tagalog
        self.dictionary[.tahitian] = tahitian
        self.dictionary[.tajik] = tajik
        self.dictionary[.tamil] = tamil
        self.dictionary[.tatar] = tatar
        self.dictionary[.telugu] = telugu
        self.dictionary[.thai] = thai
        self.dictionary[.tibetan] = tibetan
        self.dictionary[.tigrinya] = tigrinya
        self.dictionary[.tonga] = tonga
        self.dictionary[.tsonga] = tsonga
        self.dictionary[.turkish] = turkish
        self.dictionary[.turkmen] = turkmen
        self.dictionary[.twi] = twi
        self.dictionary[.ukEnglish] = ukEnglish
        self.dictionary[.ukrainian] = ukrainian
        self.dictionary[.urdu] = urdu
        self.dictionary[.usEnglish] = usEnglish
        self.dictionary[.uyghur] = uyghur
        self.dictionary[.uzbek] = uzbek
        self.dictionary[.venda] = venda
        self.dictionary[.vietnamese] = vietnamese
        self.dictionary[.volapük] = volapük
        self.dictionary[.wallon] = wallon
        self.dictionary[.welsh] = welsh
        self.dictionary[.westernFrisian] = westernFrisian
        self.dictionary[.wolof] = wolof
        self.dictionary[.xhosa] = xhosa
        self.dictionary[.yoruba] = yoruba
        self.dictionary[.zulu] = zulu
    }
}



